server.port: 8444

spring:
  profiles.active: native
  cloud.config.server.native.search-locations: classpath:cloud-config/

neubert.tobias.tls:
  identity-cert-resource: classpath:tls/certificate.pem
  identity-key-resource: classpath:tls/private.key
  trust-resource: classpath:tls/certificate.pem
